import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { validateBundle, explainTask, validateHandoff, MAX_INPUT_BYTES } from '../src/index.mjs';
import { validateSchema, assertSupportedSchema } from '../src/schema.mjs';
import { parseJsonRejectDuplicateKeys } from '../src/strict-json.mjs';
const load=n=>JSON.parse(readFileSync(new URL(`../examples/${n}.json`,import.meta.url),'utf8'));
const json=JSON.stringify;
const bundle=()=>load('team'), task=()=>load('task'), handoff=()=>load('handoff');
function invalid(name,change,code) {
 test(name,()=>{const b=bundle();change(b);const r=validateBundle(json(b));assert.equal(r.valid,false);assert.ok(r.errors.some(e=>e.code===code),json(r.errors));});
}
test('fictional three-role bundle passes',()=>{const r=validateBundle(json(bundle()));assert.equal(r.valid,true);assert.equal(r.role_count,3);assert.equal(r.route_count,2);});
test('different company and role IDs pass without internal registry',()=>{const r=explainTask(json(load('another-team')),json(task()));assert.equal(r.valid,true);assert.deepEqual(r.executors,['author']);assert.deepEqual(r.reviewers,['auditor']);});
test('explicit documentation route explained',()=>{const r=explainTask(json(bundle()),json(task()));assert.equal(r.valid,true);assert.equal(r.accountable,'coordinator');assert.deepEqual(r.reviewers,['reviewer']);assert.equal(r.human_approval_required,true);assert.equal('best_exec_score' in r,false);});
test('second code route and conditional required inputs pass',()=>assert.equal(explainTask(json(bundle()),json(load('code-task'))).valid,true));
test('same input yields byte-identical report',()=>assert.equal(json(explainTask(json(bundle()),json(task()))),json(explainTask(json(bundle()),json(task())))));
test('changed policy is immediately reflected, no module-load snapshot',()=>{const b=bundle();b.policy_version='example-v2';b.routes[0].require_human_approval=false;const r=explainTask(json(b),json(task()));assert.equal(r.policy_version,'example-v2');assert.equal(r.human_approval_required,false);assert.equal(explainTask(json(bundle()),json(task())).human_approval_required,true);});
test('success never claims actual authority, identity, or evidence',()=>{for(const r of [validateBundle(json(bundle())),explainTask(json(bundle()),json(task())),validateHandoff(json(bundle()),json(task()),json(handoff()))])for(const k of ['execution_authorized','runtime_enforcement','identity_verified','evidence_verified','source_files_checked','sensitive_data_scanned'])assert.equal(r[k],false,k);});
invalid('empty roles rejected',b=>b.roles=[],'SCHEMA_MINITEMS');
invalid('unknown schema version rejected',b=>b.schema_version='2','SCHEMA_CONST');
invalid('unknown bundle field rejected',b=>b.typo=true,'SCHEMA_ADDITIONALPROPERTIES');
invalid('missing mission rejected',b=>delete b.roles[0].contract.mission,'SCHEMA_REQUIRED');
invalid('malformed aliases rejected without throw',b=>b.roles[0].contract.aliases={wrong:true},'SCHEMA_TYPE');
invalid('duplicate role IDs rejected',b=>b.roles[1].contract.id='coordinator','ROLE_ID_DUPLICATE');
invalid('duplicate aliases within a role rejected',b=>b.roles[0].contract.aliases=['planning','planning'],'SCHEMA_UNIQUEITEMS');
invalid('aliases collide across roles',b=>{b.roles[0].contract.aliases=['same'];b.roles[1].contract.aliases=['same'];},'ROLE_ALIAS_COLLISION');
invalid('alias colliding with canonical ID rejected',b=>b.roles[0].contract.aliases=['reviewer'],'ROLE_ALIAS_COLLISION');
invalid('unknown delegation rejected',b=>b.roles[0].contract.authority.may_delegate_to.push('ghost'),'ROLE_REFERENCE_UNKNOWN');
invalid('unknown reports-to rejected',b=>b.roles[0].contract.authority.reports_to='ghost','ROLE_REFERENCE_UNKNOWN');
invalid('delegation self loop rejected',b=>b.roles[0].contract.authority.may_delegate_to.push('coordinator'),'ROLE_RELATION_CYCLE');
invalid('multi-role delegation cycle rejected',b=>b.roles[2].contract.authority.may_delegate_to=['coordinator'],'ROLE_RELATION_CYCLE');
invalid('reporting cycle separately rejected',b=>b.roles[0].contract.authority.reports_to='reviewer','ROLE_RELATION_CYCLE');
invalid('allowed/prohibited capability overlap rejected',b=>b.roles[1].contract.authority.prohibited_capabilities.push('filesystem.write.scoped'),'AUTHORITY_CONTRADICTION');
invalid('unknown allowed capability rejected',b=>b.roles[0].contract.authority.capabilities.push('undeclared'),'AUTHORITY_CONTRADICTION');
invalid('unknown prohibited capability rejected',b=>b.roles[0].contract.authority.prohibited_capabilities.push('undeclared'),'AUTHORITY_CONTRADICTION');
invalid('unknown read-only policy capability rejected',b=>b.policy.read_only_forbids.push('undeclared'),'POLICY_UNKNOWN_CAPABILITY');
invalid('read-only write capability rejected',b=>b.roles[2].contract.authority.capabilities.push('filesystem.write.scoped'),'AUTHORITY_CONTRADICTION');
invalid('read-only scopes rejected',b=>b.roles[2].contract.authority.allowed_write_scopes=['src/**'],'AUTHORITY_CONTRADICTION');
invalid('write-scoped role without scopes rejected',b=>b.roles[1].contract.authority.allowed_write_scopes=[],'AUTHORITY_CONTRADICTION');
invalid('write-scoped role without a non-read-only capability rejected',b=>b.roles[1].contract.authority.capabilities=['filesystem.read'],'AUTHORITY_CONTRADICTION');
invalid('operator without a non-read-only capability rejected',b=>{b.roles[1].contract.authority.authority_mode='operator';b.roles[1].contract.authority.capabilities=['filesystem.read'];},'AUTHORITY_CONTRADICTION');
test('operator with a policy-declared non-read-only capability passes',()=>{const b=bundle();b.roles[1].contract.authority.authority_mode='operator';assert.equal(validateBundle(json(b)).valid,true);});
invalid('human-only executable capabilities rejected',b=>b.roles[0].contract.authority.authority_mode='human_only','AUTHORITY_CONTRADICTION');
invalid('human-only write scopes rejected',b=>{b.roles[0].contract.authority.authority_mode='human_only';b.roles[0].contract.authority.capabilities=[];b.roles[0].contract.authority.allowed_write_scopes=['docs/**'];},'AUTHORITY_CONTRADICTION');
invalid('scope traversal syntax rejected',b=>b.roles[1].contract.authority.allowed_write_scopes=['../outside'],'WRITE_SCOPE_SYNTAX');
invalid('absolute scope rejected',b=>b.roles[1].contract.authority.allowed_write_scopes=['/outside'],'WRITE_SCOPE_SYNTAX');
invalid('ambiguous route rejected',b=>b.routes.push(structuredClone(b.routes[0])),'ROUTE_AMBIGUOUS');
invalid('unregistered routed reviewer rejected',b=>b.routes[0].reviewers=['ghost'],'ROUTE_ROLE_UNKNOWN');
invalid('declared self review rejected',b=>b.routes[0].reviewers=['implementer'],'SELF_REVIEW_DECLARED');
invalid('writable reviewer rejected',b=>{b.roles[2].contract.authority.authority_mode='write_scoped';b.roles[2].contract.authority.allowed_write_scopes=['src/**'];},'REVIEWER_NOT_READ_ONLY');
invalid('inactive routed role rejected',b=>b.roles[2].contract.status='dormant','ROUTE_ROLE_INACTIVE');
invalid('deprecated role missing replacement rejected',b=>b.roles[2].contract.status='deprecated','DEPRECATED_REPLACEMENT_REQUIRED');
invalid('invalid replacement target rejected',b=>b.roles[2].contract.replacement='ghost','REPLACEMENT_INVALID');
invalid('unknown knowledge reference rejected',b=>b.roles[0].contract.knowledge.required_knowledge.push('missing'),'KNOWLEDGE_REFERENCE_UNKNOWN');
invalid('duplicate knowledge declarations remain ambiguous',b=>b.knowledge.push(structuredClone(b.knowledge[0])),'KNOWLEDGE_ID_AMBIGUOUS');
invalid('credential-bearing URL rejected',b=>b.knowledge[0].uri='https://user:pass@example.invalid/file','KNOWLEDGE_URI_INVALID');
invalid('file URL rejected',b=>b.knowledge[0].uri='file:///tmp/example','KNOWLEDGE_URI_INVALID');
invalid('repository URI traversal rejected',b=>b.knowledge[0].uri='repository://sample/../secret','KNOWLEDGE_URI_INVALID');
test('https knowledge declaration accepted without fetch',()=>{const b=bundle();b.knowledge[0].uri='https://example.invalid/review';assert.equal(validateBundle(json(b)).valid,true);});
invalid('conditional rule condition must be declared',b=>b.roles[0].contract.contract.conditional_required_inputs[0].when.input='missing','CONDITIONAL_INPUT_CONTRACT');
invalid('conditional required must be optional',b=>b.roles[0].contract.contract.conditional_required_inputs[0].required_inputs=['missing'],'CONDITIONAL_INPUT_CONTRACT');
invalid('conditional rule cannot repeat unconditional input',b=>b.roles[0].contract.contract.conditional_required_inputs[0].required_inputs=['scope'],'CONDITIONAL_INPUT_CONTRACT');
invalid('required and optional overlap rejected',b=>b.roles[0].contract.contract.optional_inputs.push('scope'),'INPUT_REQUIRED_OPTIONAL_OVERLAP');
invalid('identical conditional rules rejected deeply',b=>b.roles[0].contract.contract.conditional_required_inputs.push(structuredClone(b.roles[0].contract.contract.conditional_required_inputs[0])),'SCHEMA_UNIQUEITEMS');
invalid('runtime-specific body rejected',b=>b.roles[0].body='read ~/.claude/agents/example.md','RUNTIME_SPECIFIC_DECLARATION');
invalid('model instruction header rejected',b=>b.roles[0].body='model: pretend-model','RUNTIME_SPECIFIC_DECLARATION');
invalid('mission prompt field is not part of public contract',b=>b.roles[0].contract.mission.prompt='ROLE.md','SCHEMA_ADDITIONALPROPERTIES');
invalid('whitespace-only body rejected',b=>b.roles[0].body='  \n ','SCHEMA_PATTERN');
test('unknown task type never falls back',()=>{const t=task();t.type='unknown';assert.ok(explainTask(json(bundle()),json(t)).errors.some(e=>e.code==='TASK_TYPE_UNROUTED'));});
test('missing task input rejected',()=>{const t=task();delete t.inputs.scope;assert.ok(explainTask(json(bundle()),json(t)).errors.some(e=>e.code==='TASK_INPUT_REQUIRED'));});
test('conditional required input triggers',()=>{const t=load('code-task');delete t.inputs.test_plan;assert.ok(explainTask(json(bundle()),json(t)).errors.some(e=>e.code==='TASK_INPUT_REQUIRED'));});
test('write executor task scope must be inside declared authority',()=>{const t=load('code-task');t.inputs.scope='secrets/production.txt';const r=explainTask(json(bundle()),json(t));assert.equal(r.valid,false);assert.ok(r.errors.some(e=>e.code==='TASK_WRITE_SCOPE_OUTSIDE_AUTHORITY'),json(r.errors));});
test('nested write scope is contained by declared subtree authority',()=>{const t=load('code-task');t.inputs.scope='src/nested/change.mjs';assert.equal(explainTask(json(bundle()),json(t)).valid,true);t.inputs.scope='src/nested/**';assert.equal(explainTask(json(bundle()),json(t)).valid,true);});
test('requested subtree cannot widen a narrower authority',()=>{const b=bundle();b.roles[1].contract.authority.allowed_write_scopes=['src/narrow/**'];const t=load('code-task');t.inputs.scope='src/**';const r=explainTask(json(b),json(t));assert.ok(r.errors.some(e=>e.code==='TASK_WRITE_SCOPE_OUTSIDE_AUTHORITY'),json(r.errors));});
test('exact write scope authorizes only the same exact path',()=>{const b=bundle();b.roles[1].contract.authority.allowed_write_scopes=['src/example.mjs'];const t=load('code-task');t.inputs.scope='src/example.mjs';assert.equal(explainTask(json(b),json(t)).valid,true);t.inputs.scope='src/**';assert.ok(explainTask(json(b),json(t)).errors.some(e=>e.code==='TASK_WRITE_SCOPE_OUTSIDE_AUTHORITY'));});
test('write task scope must use portable relative syntax',()=>{for(const scope of ['/tmp/x','../x','src/../x',false]){const t=load('code-task');t.inputs.scope=scope;const r=explainTask(json(bundle()),json(t));assert.ok(r.errors.some(e=>e.code==='TASK_WRITE_SCOPE_INVALID'),json({scope,errors:r.errors}));}});
test('boolean false is still supplied rather than missing even when write-scope validation rejects it',()=>{const t=task();t.inputs.scope=false;const r=explainTask(json(bundle()),json(t));assert.equal(r.errors.some(e=>e.code==='TASK_INPUT_REQUIRED'),false);assert.ok(r.errors.some(e=>e.code==='TASK_WRITE_SCOPE_INVALID'));});
test('read-only planning must not coerce schema input types',()=>{const t=task();t.acceptance_criteria='not-an-array';assert.equal(explainTask(json(bundle()),json(t)).valid,false);});
function badHandoff(name,change,code) {test(name,()=>{const h=handoff();change(h);const r=validateHandoff(json(bundle()),json(task()),json(h));assert.equal(r.valid,false);assert.ok(r.errors.some(e=>e.code===code),json(r.errors));});}
test('handoff fixture passes',()=>assert.equal(validateHandoff(json(bundle()),json(task()),json(handoff())).valid,true));
badHandoff('different task rejected',h=>h.task_id='another','HANDOFF_TASK_MISMATCH');
badHandoff('different objective rejected',h=>h.objective='another','HANDOFF_OBJECTIVE_MISMATCH');
badHandoff('unknown handoff target rejected',h=>h.suggested_next_agent='ghost','HANDOFF_ROLE_OUTSIDE_ROUTE');
badHandoff('self handoff rejected',h=>h.suggested_next_agent='implementer','HANDOFF_SELF');
badHandoff('undeclared edge rejected',h=>{h.from_agent='reviewer';h.suggested_next_agent='implementer';h.current_status='in_progress';},'HANDOFF_RELATION_UNDECLARED');
badHandoff('complete with unresolved items rejected',h=>{h.current_status='complete';h.unresolved=['Still incomplete'];},'HANDOFF_COMPLETE_UNRESOLVED');
badHandoff('blocked without blocker rejected',h=>h.current_status='blocked','HANDOFF_BLOCKER_MISSING');
badHandoff('confidence outside range rejected',h=>h.confidence=2,'SCHEMA_MAXIMUM');
badHandoff('empty evidence rejected',h=>h.evidence=[],'SCHEMA_MINITEMS');
badHandoff('unknown handoff field rejected',h=>h.random='hidden','SCHEMA_ADDITIONALPROPERTIES');
test('extensions supported but never interpreted as authority',()=>{const h=handoff();h.extensions={authorized:true};const r=validateHandoff(json(bundle()),json(task()),json(h));assert.equal(r.valid,true);assert.equal(r.execution_authorized,false);});
test('API rejects objects before accessor evaluation',()=>{let called=0;const r=validateBundle({get schema_version(){called++;return '0.1';}});assert.equal(called,0);assert.equal(r.errors[0].code,'INPUT_NOT_JSON_TEXT');});
test('malformed JSON rejected',()=>assert.equal(validateBundle('{').errors[0].code,'JSON_INVALID'));
test('duplicate decoded member names rejected',()=>assert.equal(validateBundle('{"a":1,"\\u0061":2}').errors[0].code,'JSON_INVALID'));
test('oversized JSON rejected',()=>assert.equal(validateBundle(' '.repeat(MAX_INPUT_BYTES+1)).errors[0].code,'INPUT_TOO_LARGE'));
test('deep nesting bounded',()=>assert.equal(validateBundle('['.repeat(66)+'0'+']'.repeat(66)).errors[0].code,'JSON_INVALID'));
test('nonfinite numeric exponent rejected anywhere',()=>{const s=json(bundle()).replace('"version":1','"version":1e999');assert.equal(validateBundle(s).errors[0].code,'NONFINITE_NUMBER');});
test('reserved JSON keys rejected anywhere',()=>assert.equal(validateBundle('{"__proto__":{}}').errors[0].code,'RESERVED_JSON_KEY'));
test('strict lexical parser retains generic JSON syntax',()=>assert.deepEqual(parseJsonRejectDuplicateKeys('{"a":[true,false,null,-1.2e3,"a\\u0062"]}'),{a:[true,false,null,-1200,'ab']}));
test('strict lexical parser rejects trailing comma and non-JSON whitespace',()=>{for(const s of ['[1,]','{"a":1,}','\u00a0{}','{} true'])assert.throws(()=>parseJsonRejectDuplicateKeys(s));});
test('strict lexical parser rejects non-text objects without coercion',()=>{let coerced=false;assert.throws(()=>parseJsonRejectDuplicateKeys({toString(){coerced=true;return '{}';}}),/JSON_INVALID/);assert.equal(coerced,false);});
test('strict lexical parser accepts actual UTF-8 byte views',()=>assert.deepEqual(parseJsonRejectDuplicateKeys(new TextEncoder().encode('{"a":1}')),{a:1}));
test('uniqueItems compares object members independent of order',()=>assert.equal(validateSchema([{a:1,b:2},{b:2,a:1}],{type:'array',uniqueItems:true}).valid,false));
test('minLength counts Unicode code points',()=>{assert.equal(validateSchema('😀',{type:'string',minLength:2}).valid,false);assert.equal(validateSchema('😀',{type:'string',maxLength:1}).valid,true);});
test('unknown schema keyword fails loudly rather than being ignored',()=>assert.throws(()=>assertSupportedSchema({type:'object',allOf:[]}),/SCHEMA_UNSUPPORTED_KEYWORD/));
test('unsupported schema dialect rejected',()=>assert.throws(()=>assertSupportedSchema({$schema:'https://json-schema.org/draft/2020-12/schema'}),/UNSUPPORTED_DIALECT/));
test('unsafe integers rejected rather than rounded into policy',()=>{const s=json(bundle()).replace('"version":1','"version":9007199254740993');assert.equal(validateBundle(s).errors[0].code,'UNSAFE_INTEGER');});
